echo Building Serial Solver...
g++ src/SerialSolver.cpp src/SudokuPuzzle.cpp src/IO.cpp -fopenmp -o sudokuSerial.out
echo Building Parallel Solver...
g++ src/ParallelSolver.cpp src/SudokuPuzzle.cpp src/IO.cpp -fopenmp -o sudokuParallel.out
echo Building Generator...
g++ src/SudokuPuzzleGen.cpp src/SudokuPuzzle.cpp -fopenmp -o gen.out
echo Compilation Complete